# Generated by Django 4.1.4 on 2023-01-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogUi', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
