# Generated by Django 4.1.4 on 2023-01-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogUi', '0004_article_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='req',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
