# Generated by Django 4.1.4 on 2023-02-20 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogUi', '0005_contact_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_text',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Choose the author'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='req',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Please Submit The Request here'),
        ),
    ]
