# Generated by Django 4.1.4 on 2023-02-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogUi', '0007_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.TextField(blank=True, max_length=250, null=True)),
                ('topics', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
