# Generated by Django 3.2.5 on 2021-12-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_field',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
